/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.menu;
import controller.DashboardController;
import controller.OrderController;
import entity.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.OrderModel;


/**
 *
 * @author Hermas
 */
public class HistoryGui extends javax.swing.JFrame {
    ArrayList<MerchantEntity> listMerchant=OrderModel.allm();
    ArrayList<PulsaEntity> listPulsa=OrderModel.allp();
    private OrderController orderC=new OrderController();
    private String notelp;

    /**
     * Creates new form HistoryGui
     */
    public HistoryGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaPulsa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTopUp = new javax.swing.JTextArea();
        resetBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        kembaliBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaPulsa.setEditable(false);
        areaPulsa.setColumns(20);
        areaPulsa.setRows(5);
        areaPulsa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                areaPulsaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(areaPulsa);

        areaTopUp.setEditable(false);
        areaTopUp.setColumns(20);
        areaTopUp.setRows(5);
        areaTopUp.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                areaTopUpAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(areaTopUp);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //refreshBtnActionPerformed(evt);
            }
        });

        kembaliBtn.setText("Kembali");
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(resetBtn)
                .addGap(58, 58, 58)
                .addComponent(hapusBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembaliBtn)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(hapusBtn)
                    .addComponent(refreshBtn)
                    .addComponent(kembaliBtn))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(73, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaTopUpAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_areaTopUpAncestorAdded
        areaTopUp.append("--Histoty EWallet--");
        for (MerchantEntity item :listMerchant){
            areaTopUp.append("Merek: "+item.getNaMerchant()+"\n");
            areaTopUp.append("No. telp"+item.getNoTelp()+"\n");
            areaTopUp.append("Nominal: "+item.getNominal()+"\n");
            
        }
        
    }//GEN-LAST:event_areaTopUpAncestorAdded

    private void areaPulsaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_areaPulsaAncestorAdded
        areaPulsa.append("--Histoty Pulsa--");
        for (PulsaEntity item :listPulsa){
            areaPulsa.append("Merek: "+item.getNaProvider()+"\n");
            areaPulsa.append("No. telp"+item.getNoTelp()+"\n");
            areaPulsa.append("Nominal: "+item.getNominal()+"\n");
            
        }
    }//GEN-LAST:event_areaPulsaAncestorAdded

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        orderC.resetOrder();
        JOptionPane.showMessageDialog(null, "Reset","Reset Berhasil",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        String inputan = JOptionPane.showInputDialog("Masukkan No. TelP");
        //JOptionPane.showInputDialog(null,"Masukkan No. telp"+notelp);
        orderC.removeOrder(inputan);
    }//GEN-LAST:event_hapusBtnActionPerformed

//    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
//        areaPulsa.append("--Histoty Pulsa--");
//        for (PulsaEntity item :listPulsa){
//            areaPulsa.append("Merek: "+item.getNaProvider()+"\n");
//            areaPulsa.append("No. telp"+item.getNoTelp()+"\n");
//            areaPulsa.append("Nominal: "+item.getNominal()+"\n");
//
//        }
//        areaTopUp.append("--Histoty EWallet--");
//        for (MerchantEntity item :listMerchant){
//            areaTopUp.append("Merek: "+item.getNaMerchant()+"\n");
//            areaTopUp.append("No. telp"+item.getNoTelp()+"\n");
//            areaTopUp.append("Nominal: "+item.getNominal()+"\n");
//
//        }

        
    //}//GEN-LAST:event_refreshBtnActionPerformed

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        new DashboardGui().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaPulsa;
    private javax.swing.JTextArea areaTopUp;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
